name: Run API Integration Tests

on:
  schedule:
    # Runs at 12:00 PM (UTC) Monday through Friday
    - cron: '0 12 * * 1-5'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  QuantiniuumAPITests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ prod ] # any number of environments can be added.
        include:
          - environment: prod
            baseUrl: "https://restful-booker.herokuapp.com"
              # more environment configs and their baseUrl can be added here to run on CI.

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '18'

    - name: Build and run tests on ${{ matrix.environment }}
      run: mvn clean test -DbaseUrl=${{ matrix.baseUrl }}

